#!/usr/bin/env bash
# Install nginx on your web-01 server.
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# Create a custom index.html file
echo "Hello World!" > /var/www/html/index.html
