#!/usr/bin/env bash
# Install nginx on your web-01 server.
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Create a custom index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart nginx
sudo service nginx restart
