#!/usr/bin/env bash

# What is a MAC address?

# The unique identifier of a network interface

# What is an IP address?

# Is to devices connected to a network what portal address is to houses
# Is a number that network devices use to connect to networks
