#!/usr/bin/env bash
# Bash Script that pings an IP Address passed as an arguement
if [ "$#" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

ping -c 5 "$ip_address"
