#!/usr/bin/env bash

# Update package lists 
apt-get update

# Install Nginx if its not installed.
if ! command -v nginx &> /dev/null
then
    apt-get install -y nginx
fi

# Check if Nginx is running, if not start it.
if ! service nginx status | grep -q "active (running)"
then
    service nginx start
fi

# Configure Nginx to listen on port 80 of all active IPv4 IPs
sed -i 's/listen 80;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default

# Check if any other service is running on port 80, if yes, stop it.
if lsof -Pi :80 -sTCP:LISTEN -t
then
    service "$(lsof -Pi :80 -sTCP:LISTEN -t | awk '{print $1}')" stop
fi

# Check if firewall is blocking port 80, if yes, allow it.
if ufw status | grep -q "Status: active"
then
    ufw allow 80
fi

# Restart Nginx
service nginx restart
