#!/usr/bin/env bash
# Displays the time for 12hrs 59minutes
hours=0
minutes=0
while [ "$hours" -le 12 ]
do
    echo "Hour: $hours"

    while [ "$minutes" -lt 59 ]
    do
        ((minutes++))
        echo "$minutes"
    done
    minutes=0
    ((hours++))
done