#!/usr/bin/env bash
# Displays the content of the current directory
for file in *
do
    if [[ ! "$file" == .* && "$file" == *-* ]]
    then
        name_part=$(echo "$file" | cut -d'-' -f2)

        echo "$name_part"
    fi
done