#!/usr/bin/env bash
# Gives information about the school file
file_path="school"

#check if the file exists
if [ -e "$file_path" ]; then
    echo "school file exists"
    
    # check if the file is empty
    if [ -s $file_path ]; then
        echo "school file is not empty"

        # check if its a regular file
        if [ -f $file_path ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi